# Generated by Django 4.2.30 on 2026-08-03

import uuid

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower


MODEL_NAMES = (
    "ItemCategory",
    "Unit",
    "Brand",
    "Manufacturer",
    "Supplier",
    "Warehouse",
    "Store",
)

INDEX_NAMES = {
    "ItemCategory": (
        "inventory_i_name_9b7fa9_idx",
        "inventory_i_deleted_37deb6_idx",
        "inventory_i_created_6926c4_idx",
    ),
    "Unit": (
        "inventory_u_name_a94b2c_idx",
        "inventory_u_deleted_837751_idx",
        "inventory_u_created_dc8fab_idx",
    ),
    "Brand": (
        "inventory_b_name_243657_idx",
        "inventory_b_deleted_6745e4_idx",
        "inventory_b_created_94d57b_idx",
    ),
    "Manufacturer": (
        "inventory_m_name_41276e_idx",
        "inventory_m_deleted_97f7e3_idx",
        "inventory_m_created_781289_idx",
    ),
    "Supplier": (
        "inventory_s_name_d435cf_idx",
        "inventory_s_deleted_8803ce_idx",
        "inventory_s_created_7e7bfa_idx",
    ),
    "Warehouse": (
        "inventory_w_name_703b74_idx",
        "inventory_w_deleted_2adf52_idx",
        "inventory_w_created_6e6d24_idx",
    ),
    "Store": (
        "inventory_s_name_b6074b_idx",
        "inventory_s_deleted_9ed657_idx",
        "inventory_s_created_5ab33c_idx",
    ),
}


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        *[
            migrations.CreateModel(
                name=model_name,
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    ("name", models.CharField(max_length=255)),
                    ("created_at", models.DateTimeField(auto_now_add=True)),
                    ("updated_at", models.DateTimeField(auto_now=True)),
                    ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ],
            )
            for model_name in MODEL_NAMES
        ],
        *[
            migrations.AddConstraint(
                model_name=model_name.lower(),
                constraint=models.UniqueConstraint(
                    Lower("name"),
                    condition=Q(("deleted_at__isnull", True)),
                    name=f"inventory_{model_name.lower()}_active_name_uniq",
                ),
            )
            for model_name in MODEL_NAMES
        ],
        *[
            migrations.AddIndex(
                model_name=model_name.lower(),
                index=models.Index(fields=["name"], name=INDEX_NAMES[model_name][0]),
            )
            for model_name in MODEL_NAMES
        ],
        *[
            migrations.AddIndex(
                model_name=model_name.lower(),
                index=models.Index(
                    fields=["deleted_at"], name=INDEX_NAMES[model_name][1]
                ),
            )
            for model_name in MODEL_NAMES
        ],
        *[
            migrations.AddIndex(
                model_name=model_name.lower(),
                index=models.Index(
                    fields=["created_at"], name=INDEX_NAMES[model_name][2]
                ),
            )
            for model_name in MODEL_NAMES
        ],
    ]
