# Generated by Django 4.2.30 on 2026-08-03

from decimal import Decimal
import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_reference_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=100)),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=255)),
                ("generic_name", models.CharField(blank=True, max_length=255)),
                ("track_batch", models.BooleanField(default=False)),
                ("track_expiry", models.BooleanField(default=False)),
                ("track_serial", models.BooleanField(default=False)),
                (
                    "minimum_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.itemcategory",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.manufacturer",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="inventory_i_name_637656_idx"),
                    models.Index(
                        fields=["is_active", "name"],
                        name="inventory_i_is_acti_0c7d4b_idx",
                    ),
                    models.Index(
                        fields=["deleted_at"], name="inventory_i_deleted_79e294_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="inventory_item_active_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("barcode__isnull", False)
                ),
                fields=("barcode",),
                name="inventory_item_active_barcode_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("minimum_stock__isnull", True),
                    ("maximum_stock__isnull", True),
                    ("minimum_stock__lte", models.F("maximum_stock")),
                    _connector="OR",
                ),
                name="inv_item_stock_levels_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("reorder_level__isnull", True),
                    ("maximum_stock__isnull", True),
                    ("reorder_level__lte", models.F("maximum_stock")),
                    _connector="OR",
                ),
                name="inv_item_reorder_level_ck",
            ),
        ),
    ]
